#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: ipanzhzh
# config/data_configs.yaml

# 数据配置文件
# 包含数据集路径、预处理参数等

# 数据集配置
dataset:
  name: "MR2"
  description: "多模态谣言检测数据集"
  
  # 数据路径配置 - 使用动态路径解析
  paths:
    base_dir: "auto_detect"  # 自动检测项目根目录下的data文件夹
    train_file: "dataset_items_train.json"
    val_file: "dataset_items_val.json" 
    test_file: "dataset_items_test.json"
    processed_dir: "processed"
  
  # 标签配置
  labels:
    0: "Non-rumor"
    1: "Rumor"
    2: "Unverified"
  
  # 数据要求 - 强制使用真实数据集
  requirements:
    enforce_real_data: true  # 必须使用真实数据集，找不到就报错
    allow_demo_data: false   # 不允许使用演示数据
    min_samples_per_split: 10  # 每个split最少样本数
  
  # 数据统计
  statistics:
    total_samples: 900
    train_samples: 500
    val_samples: 300
    test_samples: 100
    num_classes: 3

# 预处理配置
processing:
  # 文本预处理
  text:
    max_length: 512
    tokenization: "mixed"  # chinese, english, mixed
    clean_text: true
    remove_urls: true
    remove_mentions: true
    remove_hashtags: false
    normalize_whitespace: true
    
    # 中文处理
    chinese:
      use_jieba: true
      custom_dict: null
      
    # 英文处理  
    english:
      use_nltk: true
      use_stopwords: true
      stemming: false
      lemmatization: false
  
  # 图像预处理
  image:
    target_size: [224, 224]
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    quality_threshold: 0.3
    
    # 数据增强
    augmentation:
      train:
        enabled: true
        horizontal_flip: 0.5
        rotation: 10
        color_jitter:
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
          hue: 0.1
      val:
        enabled: false
  
  # 图结构预处理
  graph:
    node_features: ["text_features", "user_features"]
    edge_types: ["reply", "retweet", "mention"]
    max_nodes: 1000
    max_edges: 5000

# 数据加载配置
dataloader:
  train:
    batch_size: 32
    shuffle: true
    num_workers: 4
    pin_memory: true
    drop_last: false
  
  val:
    batch_size: 64
    shuffle: false
    num_workers: 4
    pin_memory: true
    drop_last: false
    
  test:
    batch_size: 64
    shuffle: false
    num_workers: 4
    pin_memory: true
    drop_last: false

# 数据分析配置
analysis:
  # 可视化配置
  visualization:
    colors:
      primary: "#FF6B6B"
      secondary: "#4ECDC4"
      tertiary: "#45B7D1"
      accent: "#96CEB4"
      warning: "#FFEAA7"
      info: "#DDA0DD"
      success: "#98FB98"
    
    chart_size: [12, 8]
    dpi: 300
    style: "whitegrid"
    
  # 统计分析
  statistics:
    text_analysis: true
    image_analysis: true
    annotation_analysis: true
    correlation_analysis: true
  
  # 报告生成
  report:
    format: "markdown"  # markdown, html, pdf
    include_plots: true
    save_raw_data: true

# 验证配置
validation:
  # 数据质量检查
  quality_check:
    min_text_length: 5
    max_text_length: 1000
    min_image_size: [50, 50]
    max_image_size: [2000, 2000]
    allowed_image_formats: ["jpg", "jpeg", "png", "bmp"]
  
  # 完整性检查
  completeness:
    require_text: true
    require_image: false  # 图像可选
    require_label: true
  
  # 一致性检查
  consistency:
    check_label_range: true
    check_file_existence: true
    check_encoding: true

# 数据增强配置
augmentation:
  # 文本增强
  text:
    enabled: false  # 默认关闭，按需开启
    methods:
      - name: "synonym_replacement"
        prob: 0.1
        params:
          n: 2
      - name: "random_insertion"
        prob: 0.1
        params:
          n: 1
      - name: "random_swap"
        prob: 0.1
        params:
          n: 1
      - name: "random_deletion"
        prob: 0.1
        params:
          p: 0.1
  
  # 图像增强  
  image:
    enabled: true
    methods:
      - name: "random_flip"
        prob: 0.5
      - name: "random_rotation"
        prob: 0.3
        params:
          degrees: [-10, 10]
      - name: "color_jitter"
        prob: 0.3
        params:
          brightness: 0.2
          contrast: 0.2

# 缓存配置
cache:
  enabled: true
  cache_dir: "cache"
  
  # 预处理结果缓存
  preprocessing:
    text_features: true
    image_features: true
    graph_features: true
    
  # 模型输出缓存
  model_outputs:
    embeddings: true
    predictions: false

# 多模态配置
multimodal:
  # 模态融合策略
  fusion:
    strategy: "early"  # early, late, hybrid
    alignment: true
    
  # 模态权重
  modality_weights:
    text: 0.6
    image: 0.4
    graph: 0.0  # 当前版本不使用图数据
  
  # 缺失模态处理
  missing_modality:
    strategy: "zero_padding"  # zero_padding, skip, interpolation
    
# 实验配置
experiment:
  # 数据分割
  split:
    method: "stratified"  # random, stratified, temporal
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
    random_seed: 42
  
  # 交叉验证
  cross_validation:
    enabled: false
    k_folds: 5
    stratified: true
    
  # 数据采样
  sampling:
    method: "none"  # none, oversample, undersample, smote
    balance_classes: false